version: "3"

networks:
 web:
  external: true

services:
 bitwarden:
  container_name: bitwarden
  image: bitwardenrs/server:alpine
  restart: always
  volumes:
  - ./bw-data/:/data/ 
  expose: 
  - 80
  networks:
  - web
  environment:
  - SIGNUPS_ALLOWED=false
  - DOMAIN=https://${BITWARDEN_DOMAIN}
  - YUBICO_CLIENT_ID=${YUBICO_CLIENTID}
  - YUBICO_SECRET_KEY=${YUBICO_SECRETKEY}
  - SMTP_HOST=${SMTP_HOST}
  - SMTP_FROM=${SMTP_FROM}
  - SMTP_PORT=${SMTP_PORT} 
  - SMTP_SSL=true
  - SMTP_USERNAME=${SMTP_USERNAME}
  - SMTP_PASSWORD=${SMTP_PASSWORD}
  labels:
  - 'traefik.enable=true'
  - 'traefik.docker.network=web'
  - 'traefik.port=80'
  - 'traefik.frontend.rule=Host:${BITWARDEN_DOMAIN}'