version: '3.3'

volumes:
 bitwarden:

services:
 bitwarden:
  container_name: bitwarden
  image: bitwardenrs/server:alpine
  restart: always
  volumes:
  - bitwarden:/data/ 
  expose: 
  - 80
  env_file: .env
  labels:
  - traefik.enable=true
  - traefik.http.routers.bitwarden.tls=true
  - traefik.http.routers.bitwarden.rule=Host(`${BITWARDEN_DOMAIN}`)
  - traefik.http.routers.bitwarden.entrypoints=web-secure
  - traefik.http.routers.bitwarden.tls.certresolver=mytlschallenge
